### ISSUE TITLE
Login command gives an error

### ISSUE THREAD

**Issue by adrianb93** [spatie/github-actions-watcher#9]
I was in a directory for a private GitHub repo. I ran:

```
actions-watcher login
```

...and got this error immediately:

```
In LoginCommand.php line 30:
                                          
  Undefined array key "verification_uri"
```

I'm running:

- PHP 8.1.4
- Version 1.0.7
- MacOS 12.3 on Apple Silicon
- I'm using the 1Password 8 SSH key management if that might be relevant

**Comment by Nielsvanpach** [comment]
I'm able to reproduce the issue on a private repository. I will look into a fix!

**Comment by freekmurze** [comment]
The problem should be resolved. Try again and let us know if it works for you now.
